### ISSUE TITLE
Allow changing the container environment at runtime

### ISSUE THREAD

**Issue by insidegui** [edorphy/CloudKitWebServices#1]
It is sometimes useful to be able to use the production environment in a debug build to test something. Currently, the environment is set to `.development` automatically for debug builds, and to `.production` for release builds, which I think is a great default, but it would be neat if the user of the library could override that manually if they want to.

If the idea is to replicate the CloudKit framework more closely, then this change could be provided at compile time with a flag different from `DEBUG`, which would take the place of the entitlement in the original framework.

Updated by Eric:
- [x] Dynamic environment selection via initializer
- [x] Dynamic environment selection via configuration

**Comment by edorphy** [comment]
Added to CKWSContainer.Configuration in 1c3d317d486419eaab30a679056ad7c853ac1fa0

Closing out.
